CREATE TABLE IF NOT EXISTS mpa (
	id INTEGER PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar NOT NULL,
	description varchar(200),
	release_date DATE NOT NULL,
	duration int,
	mpa_id INTEGER REFERENCES mpa (id)
);


CREATE TABLE IF NOT EXISTS genre (
	id INTEGER PRIMARY KEY,
	name varchar NOT NULL
);


CREATE TABLE IF NOT EXISTS film_genre (
	film_id INTEGER REFERENCES film (id),
	genre_id INTEGER REFERENCES genre (id)
);


CREATE TABLE IF NOT EXISTS users (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar NOT NULL,
	login varchar NOT NULL,
	name varchar NOT NULL,
	birthday DATE
);


CREATE TABLE IF NOT EXISTS user_friend (
	user_id INTEGER REFERENCES users (id),
	friend_id INTEGER REFERENCES users (id)
);


CREATE TABLE IF NOT EXISTS film_like (
	film_id INTEGER REFERENCES film (id),
	user_id INTEGER REFERENCES users (id)
);